### ISSUE TITLE
“NoSuchMethodErrors” due to multiple versions of org.apache.zookeeper:zookeeper

### ISSUE THREAD

**Issue by Bing-ok** [javahongxi/whatsmars#16]
## Issue description:
There are multiple versions of **_org.apache.zookeeper:zookeeper_** in **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_**. As shown in the following dependency tree, according to Maven's "nearest wins" strategy, only **_org.apache.zookeeper:zookeeper:3.4.8_** can be loaded, **_org.apache.zookeeper:zookeeper:3.6.0_** will be shadowed.

However, several methods defined in shadowed version **_org.apache.zookeeper:zookeeper:3.6.0_** are referenced by client project via **_org.apache.curator:curator-recipes:5.1.0_** but missing in the actually loaded version **_org.apache.zookeeper:zookeeper:3.4.8_**.

For instance, the following missing method(defined in **_org.apache.zookeeper:zookeeper:3.6.0_**) are actually referenced by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_**, which will introduce a runtime error(i.e., "NoSuchMethodError") into **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_**.

1. **_org.apache.zookeeper.ZooKeeper: void removeAllWatches(java.lang.String,org.apache.zookeeper.Watcher$WatcherType,boolean)_** is invoked by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_** via the following path:
<pre><code>
Invocation path------
&lt;org.hongxi.whatsmars.dubbo.demo.consumer.AsyncConsumer2: void main(java.lang.String[])&gt; whatsmars-master/whatsmars-dubbo/whatsmars-dubbo-consumer/target/classes
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: int read()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: void advance()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream openStream()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream sliceStream(java.io.InputStream)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.Closer: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.framework.recipes.watch.PersistentWatcher: void close()&gt; Respository/org/apache/curator/curator-recipes/5.1.0/curator-recipes-5.1.0.jar
&lt;org.apache.curator.framework.imps.RemoveWatchesBuilderImpl: java.lang.Object forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.RemoveWatchesBuilderImpl: java.lang.Void forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.RemoveWatchesBuilderImpl: void pathInForeground(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.zookeeper.ZooKeeper: void removeAllWatches(java.lang.String,org.apache.zookeeper.Watcher$WatcherType,boolean)&gt;
</code></pre>

2. **_org.apache.zookeeper.ZooKeeper: void removeWatches(java.lang.String,org.apache.zookeeper.Watcher,org.apache.zookeeper.Watcher$WatcherType,boolean)_** is invoked by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_** via the following path:
<pre><code>
Invocation path------
&lt;org.hongxi.whatsmars.dubbo.demo.consumer.AsyncConsumer2: void main(java.lang.String[])&gt; whatsmars-master/whatsmars-dubbo/whatsmars-dubbo-consumer/target/classes
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: int read()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: void advance()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream openStream()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream sliceStream(java.io.InputStream)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.Closer: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.framework.recipes.watch.PersistentWatcher: void close()&gt; Respository/org/apache/curator/curator-recipes/5.1.0/curator-recipes-5.1.0.jar
&lt;org.apache.curator.framework.imps.RemoveWatchesBuilderImpl: java.lang.Object forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.RemoveWatchesBuilderImpl: java.lang.Void forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.RemoveWatchesBuilderImpl: void pathInForeground(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.zookeeper.ZooKeeper: void removeWatches(java.lang.String,org.apache.zookeeper.Watcher,org.apache.zookeeper.Watcher$WatcherType,boolean)&gt;
</code></pre>

3. **_org.apache.zookeeper.ZooKeeper: boolean close(int)_** is invoked by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_** via the following path:
<pre><code>
Invocation path------
&lt;org.hongxi.whatsmars.dubbo.demo.consumer.AsyncConsumer2: void main(java.lang.String[])&gt; whatsmars-master/whatsmars-dubbo/whatsmars-dubbo-consumer/target/classes
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: int read()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: void advance()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream openStream()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream sliceStream(java.io.InputStream)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.Closer: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.ConnectionState: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.ConnectionState: void close(int)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.HandleHolder: void closeAndClear(int)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.HandleHolder: void internalClose(int)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.zookeeper.ZooKeeper: boolean close(int)&gt;
</code></pre>

4. **_org.apache.zookeeper.admin.ZooKeeperAdmin: void reconfigure(java.util.List,java.util.List,java.util.List,long,org.apache.zookeeper.AsyncCallback$DataCallback,java.lang.Object)_** is invoked by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_** via the following path:
<pre><code>
Invocation path------
&lt;org.hongxi.whatsmars.dubbo.demo.consumer.AsyncConsumer2: void main(java.lang.String[])&gt; whatsmars-master/whatsmars-dubbo/whatsmars-dubbo-consumer/target/classes
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: int read()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: void advance()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream openStream()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream sliceStream(java.io.InputStream)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.Closer: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2$3: void close()&gt; Respository/org/apache/curator/curator-recipes/5.1.0/curator-recipes-5.1.0.jar
&lt;org.apache.curator.framework.imps.DeleteBuilderImpl: java.lang.Object forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.DeleteBuilderImpl: java.lang.Void forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.CuratorFrameworkImpl: void processBackgroundOperation(org.apache.curator.framework.imps.OperationAndData,org.apache.curator.framework.api.CuratorEvent)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.CuratorFrameworkImpl: void performBackgroundOperation(org.apache.curator.framework.imps.OperationAndData)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.OperationAndData: void callPerformBackgroundOperation()&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.ReconfigBuilderImpl: void performBackgroundOperation(org.apache.curator.framework.imps.OperationAndData)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.zookeeper.admin.ZooKeeperAdmin: void reconfigure(java.util.List,java.util.List,java.util.List,long,org.apache.zookeeper.AsyncCallback$DataCallback,java.lang.Object)&gt;
</code></pre>

5. **_org.apache.zookeeper.admin.ZooKeeperAdmin: void init(java.lang.String,int,org.apache.zookeeper.Watcher,boolean)_** is invoked by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_** via the following path:
<pre><code>
Invocation path------
&lt;org.hongxi.whatsmars.dubbo.demo.consumer.AsyncConsumer2: void main(java.lang.String[])&gt; whatsmars-master/whatsmars-dubbo/whatsmars-dubbo-consumer/target/classes
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: int read()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: void advance()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream openStream()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream sliceStream(java.io.InputStream)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.Closer: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.ConnectionState: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.ConnectionState: void close(int)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.HandleHolder: void closeAndClear(int)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.HandleHolder: void internalClose(int)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.HandleHolder$1: org.apache.zookeeper.ZooKeeper getZooKeeper()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.utils.DefaultZookeeperFactory: org.apache.zookeeper.ZooKeeper newZooKeeper(java.lang.String,int,org.apache.zookeeper.Watcher,boolean)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.zookeeper.admin.ZooKeeperAdmin: void init(java.lang.String,int,org.apache.zookeeper.Watcher,boolean)&gt;
</code></pre>

6. **_org.apache.zookeeper.ZooKeeper: void addWatch(java.lang.String,org.apache.zookeeper.AddWatchMode,org.apache.zookeeper.AsyncCallback$VoidCallback,java.lang.Object)_** is invoked by **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_** via the following path:
<pre><code>
Invocation path------
&lt;org.hongxi.whatsmars.dubbo.demo.consumer.AsyncConsumer2: void main(java.lang.String[])&gt; whatsmars-master/whatsmars-dubbo/whatsmars-dubbo-consumer/target/classes
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: int read()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.MultiInputStream: void advance()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream openStream()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.ByteSource$SlicedByteSource: java.io.InputStream sliceStream(java.io.InputStream)&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.shaded.com.google.common.io.Closer: void close()&gt; Respository/org/apache/curator/curator-client/5.1.0/curator-client-5.1.0.jar
&lt;org.apache.curator.framework.recipes.locks.InterProcessSemaphoreV2$3: void close()&gt; Respository/org/apache/curator/curator-recipes/5.1.0/curator-recipes-5.1.0.jar
&lt;org.apache.curator.framework.imps.DeleteBuilderImpl: java.lang.Object forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.DeleteBuilderImpl: java.lang.Void forPath(java.lang.String)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.CuratorFrameworkImpl: void processBackgroundOperation(org.apache.curator.framework.imps.OperationAndData,org.apache.curator.framework.api.CuratorEvent)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.CuratorFrameworkImpl: void performBackgroundOperation(org.apache.curator.framework.imps.OperationAndData)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.OperationAndData: void callPerformBackgroundOperation()&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.curator.framework.imps.AddWatchBuilderImpl: void performBackgroundOperation(org.apache.curator.framework.imps.OperationAndData)&gt; Respository/org/apache/curator/curator-framework/5.1.0/curator-framework-5.1.0.jar
&lt;org.apache.zookeeper.ZooKeeper: void addWatch(java.lang.String,org.apache.zookeeper.AddWatchMode,org.apache.zookeeper.AsyncCallback$VoidCallback,java.lang.Object)&gt;
</code></pre>

## Suggested fixing solutions:
1. Use configuration &lt;dependencyManagement&gt;  to unify the version of library **_org.apache.zookeeper:zookeeper_** to be **_3.6.0_** in the pom file.
2. Declare a direct dependency **_org.apache.zookeeper:zookeeper:3.6.0_** in the **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_**'s pom file.
3. Use &lt;exclude&gt; to exclude **_org.apache.zookeeper:zookeeper:3.4.8_** in the **_whatsmars/whatsmars-dubbo/whatsmars-dubbo-consumer_**'s pom file

Please let me know which solution do you prefer? I can submit a PR to fix it.

Thank you very much for your attention.
Best regards,

## Dependency tree----
<pre><code>
[INFO] org.hongxi:whatsmars-dubbo-consumer:jar:JAWS.SR1
[INFO] +- org.hongxi:whatsmars-dubbo-api:jar:JAWS.SR1:compile
[INFO] |  \- (org.projectlombok:lombok:jar:1.18.18:compile - omitted for duplicate)
[INFO] +- org.apache.dubbo:dubbo:jar:2.7.3:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.4:compile (version managed from 4.3.16.RELEASE)
[INFO] |  |  +- org.springframework:spring-aop:jar:5.3.4:compile
[INFO] |  |  |  +- (org.springframework:spring-beans:jar:5.3.4:compile - omitted for duplicate)
[INFO] |  |  |  \- (org.springframework:spring-core:jar:5.3.4:compile - omitted for duplicate)
[INFO] |  |  +- org.springframework:spring-beans:jar:5.3.4:compile
[INFO] |  |  |  \- (org.springframework:spring-core:jar:5.3.4:compile - omitted for duplicate)
[INFO] |  |  +- org.springframework:spring-core:jar:5.3.4:compile
[INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.3.4:compile
[INFO] |  |  \- org.springframework:spring-expression:jar:5.3.4:compile
[INFO] |  |     \- (org.springframework:spring-core:jar:5.3.4:compile - omitted for duplicate)
[INFO] |  +- org.javassist:javassist:jar:3.24.1-GA:compile (version managed from 3.20.0-GA)
[INFO] |  +- (io.netty:netty-all:jar:4.1.59.Final:compile - version managed from 4.1.25.Final; omitted for duplicate)
[INFO] |  +- com.google.code.gson:gson:jar:2.8.6:compile (version managed from 2.8.5)
[INFO] |  \- org.yaml:snakeyaml:jar:1.27:compile (version managed from 1.20)
[INFO] +- com.101tec:zkclient:jar:0.9:compile
[INFO] |  \- <b>org.apache.zookeeper:zookeeper:jar:3.4.8:compile</b>
[INFO] |     +- jline:jline:jar:0.9.94:compile
[INFO] |     \- io.netty:netty:jar:3.7.0.Final:compile
[INFO] +- org.apache.curator:curator-recipes:jar:5.1.0:compile
[INFO] |  \- org.apache.curator:curator-framework:jar:5.1.0:compile
[INFO] |     \- org.apache.curator:curator-client:jar:5.1.0:compile
[INFO] |        +- <b>(org.apache.zookeeper:zookeeper:jar:3.6.0:compile - omitted for conflict with 3.4.8)</b>
[INFO] |        +- com.google.guava:guava:jar:20.0:compile (version managed from 27.0.1-jre)
[INFO] |        \- (org.slf4j:slf4j-api:jar:1.7.30:compile - version managed from 1.7.25; omitted for duplicate)
[INFO] +- com.alibaba:fastjson:jar:1.2.70:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO] +- io.netty:netty-all:jar:4.1.59.Final:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.18:compile
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:2.2:test (version managed from 1.3)
[INFO] |     \- org.hamcrest:hamcrest:jar:2.2:test
[INFO] +- org.mockito:mockito-core:jar:3.6.28:test
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.10.20:test (version managed from 1.10.18)
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.20:test (version managed from 1.10.18)
[INFO] |  \- org.objenesis:objenesis:jar:3.1:test
[INFO] +- org.hamcrest:hamcrest-library:jar:2.2:test
[INFO] |  \- (org.hamcrest:hamcrest-core:jar:2.2:test - version managed from 1.3; omitted for duplicate)
[INFO] \- org.assertj:assertj-core:jar:3.18.1:test
</code></pre>

**Comment by javahongxi** [comment]
Thanks, I fixed it, just removed `com.101tec:zkclient`.

**Comment by Bing-ok** [comment]
Thanks for your support! @javahongxi
