### ISSUE TITLE
Wiki中错别字

### ISSUE THREAD

**Issue by hb0730** [javahongxi/whatsmars#17]
![image](https://user-images.githubusercontent.com/33956166/115168008-2184a800-a0ec-11eb-9b89-88a25b0a7eef.png)

**Comment by hb0730** [comment]
[JUC JMM与线程安全](https://github.com/javahongxi/whatsmars/wiki/JUC-JMM%E4%B8%8E%E7%BA%BF%E7%A8%8B%E5%AE%89%E5%85%A8)

**Comment by javahongxi** [comment]
好的😁
